version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - appdata:/saved_charts
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - celery
      - redis
  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile_celery
    command: celery -A sql_app worker -l info
    volumes:
      - appdata:/saved_charts
      - .:/app
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
volumes:
  pgdata:
  appdata: